### ISSUE TITLE
Multisig addresses versions are '3', same as Bitcoin

### ISSUE THREAD

**Issue by aspect** [litecoin-project/litecoin#179]
Gentlemen,

We are doing massive amounts of work with Litecoin and Bitcoin in our project.  This project extensively uses Multi Signature addresses.  Naturally (and I saw there was an issue closed previously related to this, but couldn't find it) Litecoin Multi Signature addresses are indistinguishable from Bitcion as their version prefix appears as '3'...

This is creating a lot of confusion, even among our developers as we exchange addresses during testing.  I myself spent few minutes today on blockchain.info wondering why a transaction was not transmitted, just to realize that it was an LTC multisig transaction. Moreover, I am concerned that issuing a transaction to address starting with '3' on Bitcoin network will result in a loss of funds and creating serious burden for users as they may have to extract their private keys in effort to convert them between networks (if that is even feasible).

I perfectly realize the scale of the network and that deploying that kind of change is virtually impossible without breaking multisig support, hence I would like to propose the following:  We introduce support for A and B cases, where A is version '3' and B will be another version, such as '4'.  We roll out this change in the next release.  We continue issuing '3' in RPC functions.  We wait for a year or so to disable version '3' or can even leave it there.  As long as we support '4' and documentation states that clearly, then I don't see any problems with use doing this in a staged manner.

@wtogami if you are willing to supervise, I can work on this with my team, submit the necessary changes and supervise the transition over the coming year.

**Comment by franko-org** [comment]
Why not accept both? That way it doesn't cause any problems.

**Comment by losh11** [comment]
@franko-org wouldn't that still hold the confusion?

**Comment by losh11** [comment]
@aspect any new work done on your BIP (or shall I say 'LIP')?
A lot of people have recently been reporting of an exchange accidentally sending to Bitcoin multisig addresses...

**Comment by keivibi** [comment]
Hi all,
Since multisig use with each day is becoming more and more common. More and More users are finding themselves sending LTC to bitcoin multisig address by mistake. This issue is due to the fact that the litecoin core does not differentiate a BTC multisig address from LTC multisig address. 

Until a final working solution to this issue is found I propose the following:
*Update the litecoin client with a warning that when a multisig address is entered the client will display a message saying:
"Warning! Multisig address added. Please DOUBLE CHECK that this is a Litecoin multisignature address and not Bitcoin".

This can be done NOW, and we don't have to wait for a hard fork to at least address this issue some how.

More info on the below threads:
Topic: Sent litecoin to bitcoin address by mistake. Can you help?
https://litecointalk.org/index.php?topic=26513.0

Topic: Sent litecoins to bitcoin multisig address. Any way to recover them? 
https://litecointalk.org/index.php?topic=26230.0

**Comment by keivibi** [comment]
@aspect 
>Coincidentally, address version which results in the letter 'M' is what is currently being proposed. We are currently examining this to ensure that existing 3rd party clients handle the change without any adverse effects.

Can you please give a link with more information about this? Thanks.

**Comment by TheRealMage** [comment]
@aspect @wtogami @coblee @thrasher- 

Someone on reddit burned some coins by mistake by sending them to a BTC multi sig address, and was talking to @losh11 about this when he pointed me to this thread.

https://www.reddit.com/r/litecoin/comments/3rypng/why_i_sold_my_ltc_recently_community_looking_to/

Was a proposal ever created for this issue? 

If this does require a hard fork, I am more than happy to ensure that it receives the attention it needs in order for everyone to update appropriately. The last soft fork went off very well, and I feel we can do this without serious issues. Please advise, thank you.

**Comment by wtogami** [comment]
I think the time to do this would be:

* After the rebase to 0.12, which is important to go smoothly for other security/robustness reasons to make the existing network more resistant to attack than it is now.
* Probably after a hardfork decision is made for Bitcoin, which may fix several major long-standing issues including SIGOPS counting, UTXO cost, tx malleability and also allow for safer block size increase.  If we do a Litecoin hardfork, might as well wait for an upcoming hardfork that solves several problems at once.

**Comment by losh11** [comment]
Makes sense. Might take a while though.

**Comment by thrasher-** [comment]
+1 for Warren's suggestion, can implement many other hardfork changes during a single hardfork event. That way, it eliminates having to burden all users multiple times forcing them to update (usually takes a while before the majority upgrades to the latest version).

**Comment by TheRealMage** [comment]
@wtogami @thrasher- Thanks for the thoughts. I agree that if we need to hardfork for several reasons we should wait to lump them all at once. However that is a long list of issues to address, and as far as I know there are no concrete solutions to any of those (well except SIGOPS counting, not sure what that is. And I assume UTXO cost is the fee structure or is this incorrect?).

@wtogami I would like to mention something in the development and technical discussions section. Would you like to do this or would you like me to do so?

**Comment by Hothza** [comment]
Hi, 
what about testnet (p2pkh: 0x6F,  p2sh: 0xC4) - are this values will be also changed?

**Comment by losh11** [comment]
@thrasher- @wangxinxi is this being addressed in 0.13.1?

**Comment by coblee** [comment]
We are going to change the p2sh (i.e. multisig) addresses in Litecoin to start with N. But we will still continue to support addresses that start with 3.

**Comment by coblee** [comment]
Actually, we are leaning towards supporting version 50 (first letter 'M'). M for multisig.

**Comment by losh11** [comment]
Will multisig prefix '3' addresses eventually be depreciated, or will both be supported. So something like Litecoin Core P2SH address generation favouring the prefix 'M'?

**Comment by losh11** [comment]
@shaolinfry I believe this was addressed in c0d7b3b?

**Comment by shaolinfry** [comment]
@losh11 not merged. There will be a new PR by @wangxinxi

**Comment by shaolinfry** [comment]
Added in #279

**Comment by shaolinfry** [comment]
This will be part of 0.13.3
