### ISSUE TITLE
Payment to yourself type is not handled correctly!

### ISSUE THREAD

**Issue by Ghaunt** [litecoin-project/litecoin#213]
I sent a payment to myself, it debited correctly but never re-credit my account after that. Looking at history like: https://block-explorer.com/address/Ld1K5tYwg9k1oa4YZC29RQi7QYVWgpEA65 worked well but not on the LiteCoin-Core client application.

In the transactions tab in the "address" it show this "(n/a)"
In my balance available it stuck at 0.009 and the pending 0.00
It show that the transactioin is confirmed with 4861 so far.

**Comment by thrasher-** [comment]
Try launching the client with -rescan, it should take a minute or two to complete and that should resolve the issue.

As part of testing, I do this quite frequently and haven't been able to replicate this. Is your client up to date with the latest block height?

**Comment by Ghaunt** [comment]
I do the -rescan. I saw it doing it. But still the same.

Here's my transactions:

20:49:25
￼
[
{
"account" : "Main",
"address" : "Ld1K5tYwg9k1oa4YZC29RQi7QYVWgpEA65",
"category" : "receive",
"amount" : 0.01000000,
"vout" : 11,
"confirmations" : 6161,
"blockhash" : "f59c01e7ceaefe54f4b1d448d88aad701b4ac637c1634430fca9fd2d98f00561",
"blockindex" : 4,
"blocktime" : 1438912829,
"txid" : "26b0ec6a89257330f0f24635d728f22a7a98b82d09d04484d641a2a28756e10a",
"walletconflicts" : [
],
"time" : 1438912757,
"timereceived" : 1438912757
},
{
"account" : "Main",
"address" : "Ld1K5tYwg9k1oa4YZC29RQi7QYVWgpEA65",
"category" : "receive",
"amount" : 0.00100000,
"vout" : 0,
"confirmations" : 6152,
"blockhash" : "4cd49eec21195cdc47b7c932dbaba6b367d74739c15c969066e5cd55b44513f5",
"blockindex" : 18,
"blocktime" : 1438913561,
"txid" : "0a0e7479f146c6c5070b2e6cde6495f6381d7da958d29173a1ca4232be36954a",
"walletconflicts" : [
],
"time" : 1438913473,
"timereceived" : 1438913473
},
{
"account" : "",
"address" : "Ld1K5tYwg9k1oa4YZC29RQi7QYVWgpEA65",
"category" : "send",
"amount" : -0.00100000,
"vout" : 0,
"fee" : -0.00100000,
"confirmations" : 6152,
"blockhash" : "4cd49eec21195cdc47b7c932dbaba6b367d74739c15c969066e5cd55b44513f5",
"blockindex" : 18,
"blocktime" : 1438913561,
"txid" : "0a0e7479f146c6c5070b2e6cde6495f6381d7da958d29173a1ca4232be36954a",
"walletconflicts" : [
],
"time" : 1438913473,
"timereceived" : 1438913473
}
]

Here what it look like at the main screen:
![ghaunt-lcscreenshot](https://cloud.githubusercontent.com/assets/300206/9319923/d750b264-4521-11e5-8e3c-d0cc10cfcd03.png)

Being the bubble it's "(n/a)"

**Comment by Ghaunt** [comment]
I saw it, it show the fee at: -0.00100000 but that's wrong. I explicitly set it to 0. That may be the problem. I'll erase the blockchain data and see if it's the same.

**Comment by thrasher-** [comment]
The transaction is correct. Initial 0.01 with fee -0.001 = 0.009. This can be verified via the tx on the blockchain as well. Sending zero fee transactions will be rejected if they don't meet the requirements (priority by age of coins, amount, whether the transaction creates a change address with an amount lower then the dust threshold), if it can't, it will show you the fee added and prompt you.

**Comment by Ghaunt** [comment]
Thank you very much, I understand. I think this can be closed.

**Comment by thrasher-** [comment]
No problem! Please let us know if you experience anything else.
